# Generated by Django 4.1.13 on 2024-08-27 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('is_candidate', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
                ('application_number', models.CharField(max_length=255, unique=True)),
                ('applicantName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('bit_number', models.CharField(max_length=255)),
                ('bit_village', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('panchyat', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=255)),
                ('police_station', models.CharField(max_length=255)),
                ('circle', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6)),
                ('correspondentAddress', models.TextField()),
                ('mobileNumber', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('disability_percentage', models.FloatField(blank=True, null=True)),
                ('disability_type', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(max_length=255)),
                ('boardUniversity', models.CharField(max_length=255)),
                ('passingYear', models.PositiveIntegerField()),
                ('total_marks', models.CharField(max_length=255)),
                ('obtained_marks', models.CharField(max_length=255)),
                ('percentage', models.FloatField()),
                ('residential_certificate_number', models.CharField(max_length=100)),
                ('residential_certificate_date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('caste_certificate_number', models.CharField(max_length=100)),
                ('caste_certificate_date', models.DateField()),
                ('draft_number', models.CharField(max_length=100)),
                ('draft_date', models.DateField()),
                ('dd_amount', models.IntegerField()),
                ('bank_name', models.CharField(max_length=255)),
                ('application_status', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('declaration', models.BooleanField(default=True)),
                ('roll_number', models.CharField(default=None, max_length=255, unique=True)),
                ('exp_circle', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_police_station', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_bit_number', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_bit_village', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_years', models.PositiveIntegerField(blank=True, null=True)),
                ('exp_remarks', models.TextField(blank=True, null=True)),
                ('is_ex_serviceman', models.BooleanField(default=False)),
                ('has_criminal_case', models.BooleanField(default=False)),
                ('criminal_case_details', models.TextField(blank=True, null=True)),
                ('identification_mark_1', models.CharField(blank=True, max_length=255)),
                ('identification_mark_2', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('exam_center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
